export const resultNodes = [
  { componentName: "SideBar", count: 1 },
  { componentName: "LayoutSideMenu", count: 1 },
  { componentName: "Layout(props: IPropsLayout)", count: 1 },
  { componentName: "MyApp", count: 1 },
  { componentName: "LayoutSubTitle", count: 5 },
  { componentName: "WriteDiaryPresenter", count: 2 },
  { componentName: "WriteDiaryContainer", count: 2 },
  { componentName: "EditDiaryPage", count: 1 },
  { componentName: "FetchDiaryPresenter", count: 1 },
  { componentName: "FetchDiaryContainer", count: 1 },
  { componentName: "FetchDiaryPage", count: 1 },
  {
    componentName: "FetchDiariesPresenter(props: IPropsFetchDiaries)",
    count: 1,
  },
  { componentName: "FetchDiariesContainer", count: 1 },
  { componentName: "FetchDiariesPage", count: 1 },
  { componentName: "WriteDiaryPage", count: 1 },
  {
    componentName: "GamePresenter(props: IPropsGamePresenter)",
    count: 1,
  },
  { componentName: "GameContainer", count: 1 },
  { componentName: "GamePage ", count: 1 },
  { componentName: "HomePresenter(props: homePageProps)", count: 1 },
  { componentName: "HomeContainer", count: 1 },
  { componentName: "Home", count: 1 },
];
export const resultLinks = [
  { source: 3, target: 2 },
  { source: 2, target: 0 },
  { source: 2, target: 1 },
  { source: 7, target: 6 },
  { source: 6, target: 5 },
  { source: 5, target: 4 },
  { source: 10, target: 9 },
  { source: 9, target: 8 },
  { source: 8, target: 4 },
  { source: 13, target: 12 },
  { source: 12, target: 11 },
  { source: 11, target: 4 },
  { source: 14, target: 6 },
  { source: 6, target: 5 },
  { source: 5, target: 4 },
  { source: 17, target: 16 },
  { source: 16, target: 15 },
  { source: 15, target: 4 },
  { source: 20, target: 19 },
  { source: 19, target: 18 },
];
